apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
  labels:
    app: go
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go
  template:
    metadata:
      labels:
        app: go
        env: dev
    spec:
      containers:
      - name: go
        image: cloudaccelerator.azurecr.io/myapp_go
        ports:
        - name:  http
          containerPort: 3000
          protocol: TCP